name: Versioning

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Please select your new version
        options:
        - major
        - minor
        - patch
        default: minor

jobs:
  Versioning:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Set Git user
      uses: fregante/setup-git-user@v2

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: New Version
      run: |
        npm version ${{ github.event.inputs.version }} -m "Version %s"
        git push --follow-tags
